title: "i-CRADLE"
description: "A proposal submitted to the NRCP Industry-level CRADLE, in partnership with SMU, DLSU, and citrus farmers in Region II, aimed at enhancing the citrus industry in Nueva Vizcaya."
theme: jekyll-theme-minimalist
markdown: kramdown
