title: "i-CRADLE"
description: "A proposal submitted by SMU, in partnership with DLSU and citrus farmers in Region II, aimed at enhancing the citrus industry in Nueva Vizcaya."
theme: jekyll-theme-minimal
markdown: kramdown
